version: '2'
services:
  mysql:
    build: mariadb/
    ports: 
     - 3306:3306
    volumes:
      - ./wordpress/sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_DATABASE=wp_afazer
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis
  webserver:
    build: .
    volumes:
      - ./wordpress:/var/www/src/public
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    ports: 
     - 80:80
    depends_on:
      - mysql
      - redis
    links:
      - mysql:mysql
      - redis:redis
    environment:
      - CI_ENV=development
      - TZ=America/Sao_Paulo
    restart: always
